%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1920  # Updated based on the new width
image_height: 1080  # Updated based on the new height
distortion_parameters:
   k1: 0.0  # No radial distortion coefficients provided, assuming no distortion
   k2: 0.0  # No radial distortion coefficients provided, assuming no distortion
   p1: 0.0  # Assuming no tangential distortion
   p2: 0.0  # Assuming no tangential distortion
projection_parameters:
   fx: 1206.8897719532354  # Updated focal length in x direction
   fy: 1206.8897719532354  # Updated focal length in y direction
   cx: 960.5  # Updated principal point x coordinate
   cy: 540.5  # Updated principal point y coordinate
